# Generated by Django 5.1.4 on 2025-01-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_booking_menu_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
