# Generated by Django 5.1.4 on 2025-01-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_rename_title_menu_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='ID',
            new_name='iD',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Inventory',
            new_name='inventory',
        ),
    ]
